### ISSUE TITLE
Unable to build locally on MacOS M2 or Linux x64 laptop

### ISSUE THREAD

**Issue by g7morris** [Islandora-Devops/isle-imagemagick#2]
Hi @nigelgbanks 

I was unable to build this image locally (either on a MacOS M2 laptop or Linux x64 laptop) following the steps in the README.md 

* `docker buildx bake --builder default` - Works on Linux but not MacOS
  * `ERROR: use `docker --context=default buildx` to switch to context "default"`
 
* missing step for MacOS `brew install nss && mkcert -install`

* `cp $(mkcert -CAROOT)/* certs/` didn't work but `cp /Users/gavin/Library/Application\ Support/mkcert/*.pem certs/` did?
  * I think the space in MacOs is the issue
 
* `REGISTRY=islandora.io docker buildx bake --builder isle-imagemagick ci --push` fails with the errors [here]( 
https://gist.github.com/g7morris/7190ca2f59c0925f7ad71af31070fbb8)

I was able to make a PR however of what I'd like to upgrade though if possible https://github.com/Islandora-Devops/isle-imagemagick/pull/1

What would you recommend for next steps?

**Comment by nigelgbanks** [comment]
> docker buildx bake --builder default - Works on Linux but not MacOS
> ERROR: use docker --context=default buildx to switch to context "default"

You can specify different build contexts for targeting different platforms. It looks like the default is not set on your system.

Following the instructions from the error, you can set up the default context, like so:

```
docker context use default
```

> missing step for MacOS brew install nss && mkcert -install

`nss` is only required for Firefox, and `mkcert` is listed as a requirement. The `mkcert` README documents the optional need for `nss` and how to install based on which platform. 

> cp $(mkcert -CAROOT)/* certs/ didn't work but cp /Users/gavin/Library/Application\ Support/mkcert/*.pem certs/ did?
> I think the space in MacOs is the issue

Seems like `mkcert` has changed the location from `/Users/NAME/.local/share/mkcert` to `/Users/NAME/Library/Application\ Support/mkcert/`.

Using quotes will resolve this.

> `REGISTRY=islandora.io docker buildx bake --builder isle-imagemagick ci --push` fails with the errors [here](https://gist.github.com/g7morris/7190ca2f59c0925f7ad71af31070fbb8)

I've opted after reading this to update the readme to instead reference [isle-builder](https://github.com/Islandora-Devops/isle-builder). To simplify multi-arch builds.

**Comment by nigelgbanks** [comment]
I'll close this for now, and if you have an issue with the new process, you can open another ticket.
